version: '3.4'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.3
    container_name: logstash
    volumes:
      - ./logstashpipeline/:/usr/share/logstash/pipeline/
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "9600:9600" #logstash
      - "12201:12201/udp"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    volumes:
      - ./elasticdata/:/usr/share/elasticsearch/data/
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200" #elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    ports:
     - "5601:5601" #kibana
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
