version: '3.4'

services:
  ecommerceapp:
    image: docker-flask-app
    build:
      dockerfile: ./Dockerfile
    environment:
      - FLASK_APP=run.py
    ports:
      - "5000"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12201"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ecommerceapp
    ports:
      - "5000:5000"